### ISSUE TITLE
Unexpectedly old (but recently scraped) result on recent applications page

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1467] opened 2020-08-25 01:07 UTC
I just looked at https://www.planningalerts.org.au/applications which tells me it has "Recent applications within the last 2 months".

I scrolled down a little and clicked on an application at random and got https://www.planningalerts.org.au/applications/1734608 - "We found this application for you on the planning authority's website about 23 hours ago. It was received by them about 15 years earlier."

I was expecting to see recent applications; having one that's 15 years old is surprising.

**Comment by jamezpolley** [comment] 2020-08-25 01:09
I *think* that this probably means we've just added this scraper, or something like that. I assume it's in the recent list because it was recently scraped for the first time? https://www.planningalerts.org.au/applications/1734608/versions doesn't show any history before 2020-08-24 02:08:17 UTC

Perhaps the date_received (2005-08-23) be a more useful field in this case?

**Comment by mlandauer** [comment] 2020-08-28 02:10
Duplicate of #1458

**Closed by mlandauer** 2020-08-28 02:10 UTC
