### ISSUE TITLE
Show number of comments on the alerts search results

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#641] opened 2015-02-16 04:17 UTC
Story: **As a user, when searching for applications, I want to know which applications others are most interested in, so that I'm aware of contentious or popular applications and have input.**

On the page where you see applications relevant to an address, it would be helpful to highlight applications that the community was interested in.

One way to do this would be to add the comment count to the applications in the search results. We could also add a sort by comment count.

Here's the current view:

![screen shot 2015-02-16 at 2 50 39 pm](https://cloud.githubusercontent.com/assets/1239550/6207146/d7afe760-b5ee-11e4-9d52-15ea6f2d5e79.png)

**Comment by henare** [comment] 2015-02-16 04:23
:+1: nice :+1:

**Comment by mlandauer** [comment] 2018-10-30 22:54
Duplicate of #866

**Closed by mlandauer** 2018-10-30 22:54 UTC
Labels: commenting
