### ISSUE TITLE
spam on planningalerts

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1526] opened 2021-08-12 00:56 UTC
A spam-like comment was reported on planningalerts https://www.planningalerts.org.au/applications/2046320#comment107001 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3srb9)

**Comment by mlandauer** [comment] 2021-08-12 00:59
This spam comment is associated with the email address "giggsmeat@gmail.com". Since comments need to be confirmed via an email that is sent to that address it looks suspiciously like this bit of spam was generated by a human using that email address. Scummy!

**Comment by mlandauer** [comment] 2021-08-12 01:01
Looks like they're based in India so really little that we can do. Let's just hope this kind of thing doesn't become common. I'm going to close this because it doesn't appear to be an automated bit of spam so there's little we can do about it other than just hide it when we find it.

**Closed by mlandauer** 2021-08-12 01:01 UTC
Labels: commenting
