### ISSUE TITLE
show how many people are signed up per council area

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1475] opened 2020-10-13 06:05 UTC
on the authorities page, show how many people are signed up for planning alerts to each of these.

**Comment by mlandauer** [comment] 2021-08-22 10:30
To implement this we need to know the boundary of the authority. See #374

**Comment by mlandauer** [comment] 2021-08-22 10:31
This issue is almost identical to #191. I think I'll close this as a duplicate of #191

**Closed by mlandauer** 2021-08-22 10:31 UTC
