### ISSUE TITLE
Allow people to search larger than 2km

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/planningalerts#1285] opened 2018-10-03 14:23 UTC
We've got some feedback that people want to see things or be alerted for things that are more than 2km away.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fygt)

**Comment by mlandauer** [comment] 2019-01-28 01:02
Duplicate of #310

**Closed by mlandauer** 2019-01-28 01:02 UTC
Labels: backlog, enhancement
