### ISSUE TITLE
Becoming a backer can fail if you're...already a backer?

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1102] opened 2017-02-09 06:07 UTC
`[PlanningAlerts/staging] ActiveRecord::RecordInvalid: Validation failed: Email has already been taken`

## Backtrace

    line 13 of [PROJECT_ROOT]/app/controllers/donations_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/32624471)

**Comment by equivalentideas** [comment] 2017-02-09 06:07
Dupe of https://github.com/openaustralia/planningalerts/issues/1101 ?

**Comment by henare** [comment] 2017-02-09 06:10
Sounds like the same problem but this wasn't caused by me having a billing problem. I think it's more likely I was a subscriber on staging so I was already in that database table. We should work out how people accidentally trying to become a backer again will work.

**Comment by equivalentideas** [comment] 2017-02-09 06:13
> We should work out how people accidentally trying to become a backer again will work.

Yep nice. I remember seeing this and pushing it out of my mind :) I was being a bit ruthless with doing the dumb thing.

**Comment by mlandauer** [comment] 2021-08-16 16:31
We're now doing all donations through donorbox

**Closed by mlandauer** 2021-08-16 16:31 UTC
Labels: bug, backers, wontfix
