### ISSUE TITLE
Streetview temporarily flashes up on mobile

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#963] opened 2016-04-19 04:09 UTC
On my mobile when I browse to an application page I now briefly see streetview. It's because #936 always includes a static map and streetview in every page (this must also mean **the page size has increased** - is that a big problem?).

What should we do about this?

I've also personally wanted the streetview back on mobile. I think this all relates back to #538.

**Comment by CloCkWeRX** [comment] 2016-04-23 04:43
Page size would have increased by 2x images which are about 13kb and 11kb respectively. 

Examples:
https://maps.googleapis.com/maps/api/streetview?size=350x200&location=-34.843921,138.534187&fov=90&sensor=false

https://maps.googleapis.com/maps/api/staticmap?zoom=16&size=350x200&maptype=roadmap&markers=color:red%7C-34.843921,138.534187&sensor=false

For the long term, it might be better to have a downloadable PDF rendering with a dedicated print layout - print css is good, but as we saw requires a lot of argument with certain browsers.

**Comment by mlandauer** [comment] 2021-08-17 05:57
I can't reproduce this problem on my mobile phone. Gosh, a lot has changed with mobiles in the last five years so who knows? Maybe it's fixed on the PlanningAlerts side? Maybe I have a different phone? Maybe phone browsers are just different and better?

**Closed by mlandauer** 2021-08-17 05:57 UTC
Labels: UX, wontfix
