### ISSUE TITLE
Add GeoJSON support to API

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1308] opened 2018-11-22 01:41 UTC
"We have used the used the data API, which is great, but wanted to know if it's possible to receive query responses in different languages. We note GeoRSS, JSON and JSONP are currently supported, however if GeoJSON were a supported format, this would allow direct native support for desktop GIS platforms like QGIS."

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hfal)

**Comment by mlandauer** [comment] 2019-01-11 22:31
GeoJSON is a very logical thing to support. It's a relatively modern standard and I think we should do it. So, moving this to "ready".

**Comment by mlandauer** [comment] 2019-02-20 20:33
Duplicate of #539

**Closed by mlandauer** 2019-02-20 20:33 UTC
Labels: api, enhancement, ready
