### ISSUE TITLE
Acknowledge that multiple DAs have been lodged at one address

### ISSUE THREAD

**Issue by katska** [openaustralia/planningalerts#1478] opened 2020-11-10 02:49 UTC
Background to this is - When I site searched for one address from a search engine 
"25 yarraville st, Robina QLD 4226" site:planningalerts.org.au the DA that came up was not the most recent one. If I jumped straight to that one I wouldn't know that the most recent one existed. 
https://www.planningalerts.org.au/?q=25+Yarraville+St%2C+Robina+QLD+4226&sort=distance

I thought we'd come across this before, but I didn't see an issue for it, so here it is again. Let's have any other DAs be visible on a DA page for a particular address.

**Comment by mlandauer** [comment] 2021-08-22 19:26
Related to #1020 and #1021.

@katska is this a duplicate of #1021?

**Closed** 2022-02-25 20:55 UTC
Labels: enhancement, wontfix
