### ISSUE TITLE
PlanningAlerts emails getting marked as spam

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#874] opened 2015-12-13 20:29 UTC
People could be missing developments that would be important/interesting to them because they're being marked as spam.

When I was doing user testing, it was mentioned to me that sometimes PlanningAlerts emails will go to spam. We've also just received an email from someone telling us that 'SpamAssassin' is marking the emails as spam.

I think if we can find out more about why this is happening, and improve the 'spammyness rating' of the emails, then that would be great for users.

The person who emailed us gave us some information that SpamAssassin provided about why it's getting marked spam:

> Content analysis details:   (5.5 points, 5.0 required)
> 
> pts rule name              description
> ---- ---------------------- --------------------------------------------------
> 3.4 RCVD_ILLEGAL_IP        Received: contains illegal IP address
> 2.1 HTML_IMAGE_RATIO_04    BODY: HTML has a low ratio of text to image area
> 0.0 HTML_MESSAGE           BODY: HTML included in message
> 0.0 T_DKIM_INVALID         DKIM-Signature header exists but is not valid

**Comment by henare** [comment] 2016-01-12 02:34
> 0.0 T_DKIM_INVALID DKIM-Signature header exists but is not valid

Hmm, that doesn't look good. Cuttlefish is supposed to take care of DKIM for us.

We also know Bigpond has been rejecting our messages and they're now being held back by Cuttlefish :angry:

**Comment by equivalentideas** [comment] 2016-01-17 23:06
A reply to an alert email got picked up as spam by my filter, here's the reason:

Predicted: Spam (99)
Subject: RE: 1 new comment on planning applications near redacted address
From: redacted email
Reason: (
    "image001.jpg",
    "image002.jpg",
    "image003.png",
    "image004.jpg",
    "image005.jpg",
    "image006.jpg",
    "image001.jpg",
    "image002.jpg",
    "image003.png",
    "image004.jpg",
    "image005.jpg",
    "image006.jpg"
) matched rule <Any Attachment Name Starts with "image001."> in SpamSieve blocklist
Date: 2016-01-18 09:28:05 +1100 (GMT+11)

**Comment by gszathmari** [comment] 2016-09-07 04:32
I think I found one potential cause of this. Here is the chat log from Slack

```
@henare: I’m doing some Spam filtering exercise and I noticed that Planningalerts emails are flagged as Spam

[2:20]  
So the emails appear to be coming from an SMTP server named `cuttlefish.oaf.org.au` 

[2:21]  
The `From: ` field in the email headers is contact@planningalerts.org.au

[2:21]  
The issue is that the SPF record of `planningalerts.org.au` doesn’t feature `cuttlefish.oaf.org.au`

[2:22]  
while the SPF record specifies ‘hard-fail’ for every SPF violation with `-all`

[2:22]  
so our Spam filter considers these emails as Spam because they are coming from an ‘illegitimate’ SMTP server not featuring in your SPF record

[2:23]  
I think you should add `cuttlefish.oaf.org.au` to the SPF record of planningalerts.org.au

[2:24]  
the SPF record of `cuttlefish.oaf.org.au` specifies the SMTP properly, you need to add something similar to the DNS record at `planningalerts.org.au`

[2:26]  
https://mxtoolbox.com/SuperTool.aspx?action=spf%3aplanningalerts.org.au

[2:27]  
https://mxtoolbox.com/SuperTool.aspx?action=spf%3acuttlefish.oaf.org.au
```

**Comment by henare** [comment] 2016-09-07 05:05
@gszathmari thanks! This is definitely something we need to fix.

https://www.mail-tester.com/web-5MUb37

![selection_001](https://cloud.githubusercontent.com/assets/48945/18300435/5f3da356-750c-11e6-8601-9d537358e5bd.png)

:fire: harsh :fire:

**Comment by henare** [comment] 2016-09-07 05:14
I've changed the SPF record to `"v=spf1 include:_spf.google.com a:cuttlefish.oaf.org.au  -all"` and we're now:

![selection_001](https://cloud.githubusercontent.com/assets/48945/18300582/a0c7cb34-750d-11e6-94c1-8c27acbadb54.png)

Which I think will go up when DNS propagates as well.

Things are green here too: https://mxtoolbox.com/SuperTool.aspx?action=spf%3aplanningalerts.org.au

**Comment by gszathmari** [comment] 2016-09-07 05:43
@henare: you are a 🌟 I'll have a look our Spam filter later and confirm if it's working properly

**Comment by gszathmari** [comment] 2016-09-08 02:15
I had a look on the email gateway logs today and I can confirm that emails coming from the SMTP server `cuttlefish.oaf.org.au` are not violating your SPF policy on `planningalerts.org.au` anymore

**Comment by henare** [comment] 2016-09-08 02:28
Thanks @gszathmari for noticing and reporting this. It will be a big help to people using PlanningAlerts :gift: 

It looks like we're pretty good now:

![selection_001](https://cloud.githubusercontent.com/assets/48945/18335035/6c38a296-75bf-11e6-98be-028a7073e8da.png)

So I'll close this.

**Closed by henare** 2016-09-08 02:28 UTC
Labels: bug, UX
