### ISSUE TITLE
An authority has published the email/street address of a commenter

### ISSUE THREAD

**Issue by henare** [openaustralia/planningalerts#1095] opened 2017-02-08 04:48 UTC
We were recently contacted by a person that was understandably upset because their email/street address had been published by Hawkesbury City Council. Obviously the council should not do this but is there something we can do to make this less likely to happen?

Maybe we could add something to the email we send to council stating the obvious - that you shouldn't publish peoples' private email and street address publicly on the internet? :disappointed:

**Comment by mlandauer** [comment] 2021-08-16 18:02
Duplicate of #1378 which is a little more specific with the proposed solution

**Closed by mlandauer** 2021-08-16 18:02 UTC
Labels: enhancement, commenting, UX, wontfix
