### ISSUE TITLE
Words with double letters being scraped wrongly

### ISSUE THREAD

**Issue by Janice80** [openaustralia/planningalerts#1288] opened 2018-10-17 05:10 UTC
I have raised this issue before however it seems to still have not been addressed – though I did get an email saying that it has been fixed. Any text that is being brought across to Planning Alerts that contains two identical letters is having one of the letters removed – for example the word Street  and Toormina, Woolgoolga, Sawtell, Coffs Harbour ect.

Can you please action this as we are getting complaints from our customers.

Regards,

Jan #
![planning alert email](https://user-images.githubusercontent.com/40417207/47063536-2f10fc80-d227-11e8-9ced-8ff8feee82d2.JPG)
![planning](https://user-images.githubusercontent.com/40417207/47063538-2fa99300-d227-11e8-8b28-921c23a07f87.JPG)

**Comment by mlandauer** [comment] 2018-10-30 22:32
Closing as a duplicate of https://github.com/planningalerts-scrapers/coffs_harbour/issues/6

**Closed by mlandauer** 2018-10-30 22:33 UTC
