### ISSUE TITLE
Masterview scraper silently failing to get alerts from Brisbane

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/planningalerts#1471] opened 2020-09-22 01:21 UTC
https://www.planningalerts.org.au/authorities/brisbane/under_the_hood
> 0 applications found for Brisbane City Council, QLD with date from 2020-09-07
> Took 1 s to import applications from Brisbane City Council, QLD

There's definitely applications on the site: https://pdonline.brisbane.qld.gov.au/MasterViewUI/Modules/ApplicationMaster/default.aspx?page=found&1=thismonth&6=F

![image](https://user-images.githubusercontent.com/216918/93836303-aed25c00-fcc5-11ea-95b7-de1ce8db7ab7.png)

I've had a quick look at the scraper and I can't see any obvious reason why this would be failing. The URL seems to be correct, the site seems to be up and running.. but no alerts scraped for two months.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31znp)

**Comment by mlandauer** [comment] 2020-09-30 02:02
Duplicate of https://github.com/planningalerts-scrapers/issues/issues/178

**Closed by mlandauer** 2020-09-30 02:02 UTC
