### ISSUE TITLE
Address autocomplete broken

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/planningalerts#1001] opened 2016-06-13 23:53 UTC
On the [home page](https://www.planningalerts.org.au), on load an alert message pops up ( see #1000 ), and after it goes the autocomplete for address lookup doesn't work. Same thing on the [signup page](https://www.planningalerts.org.au/alerts/signup).

**Comment by henare** [comment] 2016-06-14 03:33
Duplicate of #1000.

**Closed by henare** 2016-06-14 03:33 UTC
Labels: bug
